### ISSUE TITLE
Warnings go unsilenced?

### ISSUE THREAD

**Issue by ttrmw** [jeremyevans/ruby-warning#1]
In my Rails project, I'm seeing, for example:

```
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
```

And trying to silence the warnings when the test suite runs, by running:

```
Warning.ignore([:fixnum, :bignum])
```

in `config/environments/test.rb`... But this has no effect. 

Ruby version is 2.4.0.

Where am I going wrong?

**Comment by jeremyevans** [comment]
My guess is activesupport gem is required before the Warning.ignore call.  You should require warning and use Warning.ignore before bundler loads. I think that's in config/boot.rb, but my recollection of the Rails boot process is fairly hazy.

If you still can't get it to work and think this is a problem with warning, please post a self contained example showing the problem occurring outside of Rails and I'll take a look.
