### ISSUE TITLE
Get backtrace in process method

### ISSUE THREAD

**Issue by yosiat** [jeremyevans/ruby-warning#10]
Hi!

Great library :)

Is it possible to log all warnings to a file with their backtrace?

**Comment by jeremyevans** [comment]
This should work:

```ruby
warning_file = File.open(''warnings.log, 'a')
Warning.process do |str|
  warning_file.puts str
  warning_file.puts caller(6)
end
```

There's actually an easier approach if you are OK with the warnings and backtrace going to `$stderr` (you can redirect that to a file): `Warning.process{:backtrace}`
