### ISSUE TITLE
Release and bump to 1.2.1?

### ISSUE THREAD

**Issue by veganstraightedge** [jeremyevans/ruby-warning#15]
Hi Jeremy. Thanks for making this gem.

Do you have plans to cut a 1.2.1 release with those few commits from March?

We currently have this in our `Gemfile`:

```ruby
# TEMP:
# pulling from git until https://github.com/jeremyevans/ruby-warning/commit/1698be5cca1b4e527c46b52f8244c3a86c701752
# is released
gem "warning", github: "jeremyevans/ruby-warning", ref: "1698be5cca1b4e527c46b52f8244c3a86c701752"
```

And it'd be really swell if we could have this instead:

```ruby
gem "warning"
```

Thanks again. 
— Sb

**Comment by jeremyevans** [comment]
ruby-warning 1.2.1 released
