### ISSUE TITLE
Document how to use Warning with bundler

### ISSUE THREAD

**Issue by Nowaker** [jeremyevans/ruby-warning#4]
Cite from https://github.com/jeremyevans/ruby-warning/issues/1#issuecomment-281137805:

> My guess is activesupport gem is required before the Warning.ignore call. You should require warning and use Warning.ignore before bundler loads. I think that's in config/boot.rb, but my recollection of the Rails boot process is fairly hazy.

Virtually all Ruby projects use Bundler for dependency management. Please document how to use your gem in Bundler projects in README.md.

**Comment by jeremyevans** [comment]
It does seem reasonable to document that should load warning before requiring files that may cause syntax warnings (unrelated to the use of bundler).  I'll add that to the README.

**Comment by Nowaker** [comment]
Thanks!
