### ISSUE TITLE
Would like a release with the warning deduplication code

### ISSUE THREAD

**Issue by bubaflub** [jeremyevans/ruby-warning#5]
Hello,

Thanks for the ruby-warning module!  We use it at work in our CI and it's helped shake out wrong code that's been there for years.  Initially I just turned on warnings but the sheer number of warnings coming out was overwhelming.  I took the config and silenced warnings coming from gems so we only saw warnings coming from our code.  But that was still too much.  So I enabled the warning deduplication and that's been much easier to understand and fix.

I'd like a new released version of the Gem that includes 54d1d0f3ec20d58cfa568df27515b341d8bd88ef so I don't have to specify a git hash in my Gemfile.

Thanks!

**Comment by jeremyevans** [comment]
Thanks for the reminder. I agree it makes sense to get another release out.  I think I need to update the warnings for keyword argument separation as they changed before the Ruby 2.7.0 release, but after that things should be ready for release.  I'll try to put out a release in the next few days.

**Comment by jeremyevans** [comment]
I released warning 1.0.0 today with the `Warning.dedup` feature, and a few other features.
