### ISSUE TITLE
`:keyword_separation` doesn't suppress the second line from another file

### ISSUE THREAD

**Issue by AlexWayfer** [jeremyevans/ruby-warning#6]
Without:

```
/home/alex/Projects/ruby/memery/lib/memery.rb:73: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/alex/Projects/ruby/memery/spec/memery_spec.rb:28: warning: The called method `m_kwargs' is defined here

/home/alex/Projects/ruby/memery/lib/memery.rb:73: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/alex/Projects/ruby/memery/spec/memery_spec.rb:33: warning: The called method `m_double_splat' is defined here
```

With:

```ruby
require "warning"
Warning.ignore :keyword_separation, __FILE__
```

```
/home/alex/Projects/ruby/memery/spec/memery_spec.rb:28: warning: The called method `m_kwargs' is defined here

/home/alex/Projects/ruby/memery/spec/memery_spec.rb:33: warning: The called method `m_double_splat' is defined here
```

Without `__FILE__` it works, but maybe it can be improved, because the both lines are parts of single warning.

**Comment by jeremyevans** [comment]
Technically, the messages are emitted as two separate warnings, so `Warning` cannot know they are related.  The warnings actually use separate C functions (first one `rb_warn`, second one `rb_compile_warn`). Unfortunately, there is nothing we can do in this case.

**Comment by AlexWayfer** [comment]
Because `Warning.ignore :keyword_separation` is global and dangerous, I've solved this by specifying `Warning.ignore :keyword_separation, __FILE__` in both files. It's like repeating, but better, than global change.

Anyway, thank you for response and explanation.
